// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Data_LojaDiretorioCarrinho.Models
{
    public partial class BancoCarrinhoContext : DbContext
    {
        public BancoCarrinhoContext()
        {
        }

        public BancoCarrinhoContext(DbContextOptions<BancoCarrinhoContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<ProdutoClienteCarrinho> ProdutoClienteCarrinho { get; set; }
        public virtual DbSet<VwProdutoClienteCarrinho> VwProdutoClienteCarrinho { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-6G0VTBS\\SQLEXPRESS;Initial Catalog=BancoCarrinho;Integrated Security=True;TrustServerCertificate=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Cliente>(entity =>
            {
                entity.Property(e => e.CliCpf).IsFixedLength();
            });

            modelBuilder.Entity<ProdutoClienteCarrinho>(entity =>
            {
                entity.HasOne(d => d.IdClienteNavigation)
                    .WithMany(p => p.ProdutoClienteCarrinho)
                    .HasForeignKey(d => d.IdCliente)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Produto_Cliente_Carrinho_Cliente");

                entity.HasOne(d => d.IdProdutoNavigation)
                    .WithMany(p => p.ProdutoClienteCarrinho)
                    .HasForeignKey(d => d.IdProduto)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Produto_Cliente_Carrinho_Produto");
            });

            modelBuilder.Entity<VwProdutoClienteCarrinho>(entity =>
            {
                entity.ToView("VW_Produto_Cliente_Carrinho");

                entity.Property(e => e.CliCpf).IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}