// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data_LojaDiretorioCarrinho.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            ProdutoClienteCarrinho = new HashSet<ProdutoClienteCarrinho>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("cli_nome")]
        [StringLength(100)]
        [Unicode(false)]
        [DisplayName("Nome")]
        public string CliNome { get; set; }
        [Required]
        [Column("cli_endereco")]
        [StringLength(50)]
        [Unicode(false)]
        [DisplayName("Endereço")]
        public string CliEndereco { get; set; }
        [Required]
        [Column("cli_cidade")]
        [StringLength(50)]
        [Unicode(false)]
        [DisplayName("Cidade")]
        public string CliCidade { get; set; }
        [Required]
        [Column("cli_telefone")]
        [StringLength(14)]
        [Unicode(false)]
        [DisplayName("Telefone")]
        public string CliTelefone { get; set; }
        [Required]
        [Column("cli_email")]
        [StringLength(100)]
        [Unicode(false)]
        [DisplayName("E-mail")]
        public string CliEmail { get; set; }
        [Required]
        [Column("cli_cpf")]
        [StringLength(11)]
        [Unicode(false)]
        [DisplayName("CPF")]
        public string CliCpf { get; set; }

        [InverseProperty("IdClienteNavigation")]
        public virtual ICollection<ProdutoClienteCarrinho> ProdutoClienteCarrinho { get; set; }
    }
}