// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DATA_LojaDiretorioCarrinho.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            ProdutoClienteCarrinho = new HashSet<ProdutoClienteCarrinho>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(100)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [Column("endereco")]
        [StringLength(50)]
        [Unicode(false)]
        public string Endereco { get; set; }
        [Column("cidade")]
        [StringLength(50)]
        [Unicode(false)]
        public string Cidade { get; set; }

        [InverseProperty("IdClienteNavigation")]
        public virtual ICollection<ProdutoClienteCarrinho> ProdutoClienteCarrinho { get; set; }
    }
}