// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DATA_LojaDiretorioCarrinho.Models
{
    public partial class Produto
    {
        public Produto()
        {
            ProdutoClienteCarrinho = new HashSet<ProdutoClienteCarrinho>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Column("preco")]
        public double Preco { get; set; }
        [Required]
        [Column("marca")]
        [StringLength(50)]
        [Unicode(false)]
        public string Marca { get; set; }

        [InverseProperty("IdProdutoNavigation")]
        public virtual ICollection<ProdutoClienteCarrinho> ProdutoClienteCarrinho { get; set; }
    }
}