// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DATA_LojaDiretorioCarrinho.Models
{
    [Table("Produto_Cliente_Carrinho")]
    public partial class ProdutoClienteCarrinho
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idProduto")]
        public int IdProduto { get; set; }
        [Column("idCliente")]
        public int IdCliente { get; set; }
        [Column("dataCompra", TypeName = "datetime")]
        public DateTime DataCompra { get; set; }
        [Column("frete")]
        public double Frete { get; set; }

        [ForeignKey("IdCliente")]
        [InverseProperty("ProdutoClienteCarrinho")]
        public virtual Cliente IdClienteNavigation { get; set; }
        [ForeignKey("IdProduto")]
        [InverseProperty("ProdutoClienteCarrinho")]
        public virtual Produto IdProdutoNavigation { get; set; }
    }
}