// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data_LojaDiretorioCarrinho.Models
{
    [Keyless]
    public partial class VwProdutoClienteCarrinho
    {
        [Required]
        [Column("cli_cpf")]
        [StringLength(11)]
        [Unicode(false)]
        [DisplayName("CPF Cliente")]
        public string CliCpf { get; set; }
        [Required]
        [Column("cli_nome")]
        [StringLength(100)]
        [Unicode(false)]
        [DisplayName("Nome do Cliente")]
        public string CliNome { get; set; }
        [Required]
        [Column("pdt_nome")]
        [StringLength(50)]
        [Unicode(false)]
        [DisplayName("Nome do Produto")]
        public string PdtNome { get; set; }
        [Column("id")]
        public int Id { get; set; }
        [Column("idProduto")]
        [DisplayName("ID do Produto")]
        public int IdProduto { get; set; }
        [Column("idCliente")]
        [DisplayName("ID do Cliente")]

        public int IdCliente { get; set; }
        [Column("dataCompra", TypeName = "datetime")]
        [DisplayName("Data da Compra")]
        public DateTime DataCompra { get; set; }
        [Column("frete")]
        [DisplayName("Frete")]
        public double? Frete { get; set; }
    }
}